name: Test SSH Key Connection
on: [push]

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Test SSH with Key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            echo "🎉 🎉 🎉 CONEXÃO SSH BEM-SUCEDIDA! 🎉 🎉 🎉"
            echo "Usuário: $(whoami)"
            echo "Diretório: $(pwd)"
            echo "Home: $HOME"
            echo "Data/hora: $(date)"
            echo "✅ Tudo funcionando perfeitamente!"
