name: Deploy Flora (aless - simple)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # ===== BUILD (só se existir) =====
      - name: Build store (if present)
        if: ${{ hashFiles('loja-virtual/package.json') != '' }}
        working-directory: loja-virtual
        env:
          VITE_API_BASE: http://72.60.5.89:3000
        run: |
          npm ci
          npm run build

      - name: Build admin (if present)
        if: ${{ hashFiles('admin-frontend/package.json') != '' }}
        working-directory: admin-frontend
        env:
          VITE_API_BASE: http://72.60.5.89:3000
        run: |
          npm ci
          npm run build

      # ===== UPLOAD (sem sudo, via senha) =====
      - name: Upload store dist (if present)
        if: ${{ hashFiles('loja-virtual/dist/**') != '' }}
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: '22'
          source: "loja-virtual/dist/*"
          target: "${{ secrets.REMOTE_PATH }}/loja-virtual"
          strip_components: 2

      - name: Upload admin dist (if present)
        if: ${{ hashFiles('admin-frontend/dist/**') != '' }}
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: '22'
          source: "admin-frontend/dist/*"
          target: "${{ secrets.REMOTE_PATH }}/admin-frontend"
          strip_components: 2

      - name: Upload backend (all, except node_modules)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: '22'
          source: "backend-api/*"
          target: "${{ secrets.REMOTE_PATH }}/backend-api"
          overwrite: true
          rm: false

      # ===== DEPLOY backend (sem sudo, com PID) =====
      - name: Deploy backend (nohup node)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: '22'
          script: |
            set -e
            cd "${{ secrets.REMOTE_PATH }}/backend-api"

            # mata processo anterior, se houver
            if [ -f app.pid ]; then
              PID=$(cat app.pid || true)
              if [ -n "$PID" ] && ps -p "$PID" > /dev/null 2>&1; then
                kill "$PID" || true
                sleep 1
              fi
            fi

            # instala dependências e sobe em background
            npm ci --omit=dev
            nohup node index.js >/dev/null 2>&1 & echo $! > app.pid

            echo "✅ Backend iniciado (PID $(cat app.pid))"
            echo "✅ Deploy concluído (loja/admin se enviados, backend sempre)."
