name: Deploy to VPS
on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      # --- DEBUG: Verificar secrets ---
      - name: Debug secrets
        run: |
          echo "SSH_HOST: ${{ secrets.SSH_HOST }}"
          echo "SSH_USER: ${{ secrets.SSH_USER }}"
          echo "REMOTE_PATH: ${{ secrets.REMOTE_PATH }}"
          echo "SSH_PASSWORD length: ${#SECRET_PASSWORD}" 
        env:
          SECRET_PASSWORD: ${{ secrets.SSH_PASSWORD }}

      # --- TESTE SIMPLES de conexão ---
      - name: Test SSH connection
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            echo "✅ Conexão SSH bem-sucedida!"
            whoami
            pwd
