      - name: Deploy backend (nohup node)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: '22'
          script: |
            set -e
            cd "${{ secrets.REMOTE_PATH }}/backend-api"

            # mata processo anterior, se houver
            if [ -f app.pid ]; then
              PID=$(cat app.pid || true)
              if [ -n "$PID" ] && ps -p "$PID" > /dev/null 2>&1; then
                kill "$PID" || true
                sleep 1
              fi
            fi

            # instala dependências e sobe em background
            npm ci --omit=dev
            nohup node index.js >/dev/null 2>&1 & echo $! > app.pid

            echo "✅ Backend iniciado (PID $(cat app.pid))"
